#Updated keybind saves
#Sun Jun 21 23:16:04 EDT 2026
CHANGE_RIGHT.default=75
CHANGE_UP.default=80
CLEAR_LEVEL.default=67
LIST_KEYS.default=5006
MENU_BACK.default=27
PLAY_SOUND.default=76
RESET_KEYS.default=5007
SHOW_DEBUG.default=114
WALK_DOWN.default=83
WALK_LEFT.default=65
WALK_RIGHT=68
WALK_RIGHT.default=68
WALK_UP=87
WALK_UP.default=87
