#Updated keybind saves
#Sat Jun 20 03:44:10 EDT 2026
CHANGE_RIGHT.defaultk=75
CHANGE_UP.defaultk=80
CLEAR_LEVEL.defaultk=67
MENU_BACK.defaultk=27
PLAY_SOUND.defaultk=76
SHOW_DEBUG.defaultk=114
WALK_DOWN.defaultk=83
WALK_LEFT.defaultk=65
WALK_RIGHT.defaultk=68
WALK_RIGHTk=72
WALK_UP.defaultk=87
WALK_UPm=1
